spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  freemarker:
    template-loader-path: classpath:/templates/
    content-type: text/html
    cache: false
    charset: utf-8
    check-template-location: true
    expose-request-attributes: false
    expose-session-attributes: false
    request-context-attribute: req
    suffix: .ftl
  datasource:
    url: jdbc:h2:file:./data/otp_keys_db
    driverClassName: org.h2.Driver
    username: otp_keys_user
    password: password_20240901aAa-@@@
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: false
  profiles:
    active: release