server:
  port: 9999

spring:
  security:
    user:
      name: admin
      password: admin1234
  datasource:
    username: sa
    password: password
    url: jdbc:h2:file:./data/otp_keys_db


#下载链接
#jar包       wget https://github.com/doubleDimple/mfa-start/releases/latest/download/mfa-start-release.jar
#脚本        wget https://github.com/doubleDimple/mfa-start/releases/latest/download/mfa-start.sh
#配置文件    wget https://github.com/doubleDimple/mfa-start/releases/latest/download/mfa-start.yml